=== maayehkhaled/silverlight-dfa/branches/SilverlightApplication6/Input.dtd
<!ELEMENT FiniteAutomaton (InputAlphabet, States, Transitions)>
<!ELEMENT InputAlphabet (Symbol, Symbol)>
<!ELEMENT Symbol (#PCDATA)>
<!ELEMENT States (State+)>
<!ELEMENT State (#PCDATA)>
<!ATTLIST State x CDATA #REQUIRED>
<!ATTLIST State y CDATA #REQUIRED>
<!ATTLIST State start (Y|y|N|n) "N">
<!ATTLIST State accept (Y|y|N|n) "N">
<!ELEMENT Transitions (Transition, Transition+)>
<!ELEMENT Transition EMPTY>
<!-- TODO: is it possible to have a refernce to the content of 'Symbol' here? -->
<!ATTLIST Transition from CDATA #REQUIRED>
<!ATTLIST Transition symbol CDATA #REQUIRED>
<!ATTLIST Transition to CDATA #REQUIRED>

=== maayehkhaled/silverlight-dfa/SilverlightApplication6/SilverlightApplication6/testdata/Sipser.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- Modified Version of Hopcroft/Motwani/Ullman to show other node types -->
<!-- schema validation is not supported in silverlight! what an evidence of incapacity!!! -->
<!--<FiniteAutomaton xmlns="http://silverlight.dfa/Input.xsd">-->
<!DOCTYPE FiniteAutomaton SYSTEM "../Input.dtd">
<FiniteAutomaton>
  <InputAlphabet>
    <Symbol>0</Symbol>
    <Symbol>1</Symbol>
  </InputAlphabet>
  <States>
    <State x="200" y="150" start="Y">q1</State>
    <State x="300" y="150" accept="Y">q2</State>
    <State x="200" y="250">q3</State>
    
  </States>
  <Transitions>
    <Transition from="q1" symbol="b" to="q1" />
    <Transition from="q1" symbol="a" to="q2" />
	
	<Transition from="q2" symbol="a" to="q3" />
	<Transition from="q2" symbol="b" to="q3" />

	  <Transition from="q3" symbol="a" to="q2" />
	  <Transition from="q3" symbol="b" to="q1" />

  </Transitions>
</FiniteAutomaton>

=== maayehkhaled/silverlight-dfa/SilverlightApplication6/SilverlightApplication6/testdata/Default.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE FiniteAutomaton SYSTEM "../Input.dtd">
<FiniteAutomaton>
  <InputAlphabet>
    <Symbol>0</Symbol>
    <Symbol>1</Symbol>
  </InputAlphabet>
  <States>
    <State x="150" y="100" start="Y" accept="Y">q0</State>
    <State x="400" y="100" start="Y">q1</State>
    
    <State x="50" y="217" accept="Y">q2</State>
    <State x="500" y="217">q3</State>
    
    <State x="150" y="334">q4</State>
    <State x="400" y="334">q5</State>
  </States>
  <Transitions>
    <Transition from="q0" symbol="0" to="q2" />
    <Transition from="q0" symbol="1" to="q1" />
    <Transition from="q1" symbol="0" to="q3" />
    <Transition from="q1" symbol="1" to="q0" />
    <Transition from="q2" symbol="0" to="q0" />
    <Transition from="q2" symbol="1" to="q3" />
    <Transition from="q3" symbol="0" to="q1" />
    <Transition from="q3" symbol="1" to="q2" />
  </Transitions>
</FiniteAutomaton>
